server:
  port: 8806
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8003/eureka/
logging:
  level:
     org.springframework.cloud.gateway: debug