
server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lizhiweer/springBootDemo.git     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 13886187497@163.com                                              # git仓库的账号
          password: aaa2424352491                                              # git仓库的密码