server:
  port: 8805
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8003/eureka/
#    fetch-registry: false
#    register-with-eureka: false
# zuul:
#   routes:
#     aaa:
#       path: /test/**        
#       url: http://localhost:8803/
#     api:
#       path: /abc/**
#       service-id: eurekaclient

