spring:
  application:
    name: eurekaclient1
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://120.77.212.44:9411/
server:
  port: 8803
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8003/eureka/
feign:
  hystrix:
    enabled: true