server:
  port: 8003
spring:
  application:
    name: eurekaServer
eureka:
  instance:
    hostname: s1
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:8003/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false     #关闭自我保护
    eviction-interval-timer-in-ms: 60000   #清理间隔
    

